version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 99
  reviewers:
  - sony-mathew
  - sojan-official
  - subintp
  labels:
  - dependencies
  - ruby
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.91.0
    - 1.92.0
    - 1.93.0
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.7.0
    - 1.7.2
    - 1.7.3
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.12.1
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: twilio-ruby
    versions:
    - 5.46.0
    - 5.46.1
    - 5.47.0
    - 5.48.0
    - 5.49.0
    - 5.50.0
    - 5.51.0
  - dependency-name: cypress-on-rails
    versions:
    - 1.8.1
    - 1.9.1
  - dependency-name: geocoder
    versions:
    - 1.6.4
    - 1.6.5
    - 1.6.6
  - dependency-name: rails
    versions:
    - 6.0.3.5
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: database_cleaner
    versions:
    - 2.0.0
  - dependency-name: jbuilder
    versions:
    - 2.11.1
  - dependency-name: slack-ruby-client
    versions:
    - 0.16.0
  - dependency-name: browser
    versions:
    - 5.3.0
  - dependency-name: bullet
    versions:
    - 6.1.3
  - dependency-name: scout_apm
    versions:
    - 4.0.3
  - dependency-name: google-cloud-storage
    versions:
    - 1.30.0
  - dependency-name: liquid
    versions:
    - 5.0.0
  - dependency-name: brakeman
    versions:
    - 4.10.1
  - dependency-name: valid_email2
    versions:
    - 3.5.0
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
  - dependency-name: telegram-bot-ruby
    versions:
    - 0.14.0
  - dependency-name: groupdate
    versions:
    - 5.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 99
  reviewers:
  - pranavrajs
  - nithindavid
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.0
    - 6.8.0
    - 7.0.0
    - 7.1.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.13.0
    - 7.13.10
    - 7.13.14
    - 7.13.15
  - dependency-name: chart.js
    versions:
    - 2.9.4
    - 3.0.2
    - 3.1.0
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.19.0
    - 2.20.2
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.24.0
    - 8.24.1
    - 8.24.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: ionicons
    versions:
    - 5.3.0
    - 5.4.0
    - 5.5.0
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: copy-text-to-clipboard
    versions:
    - 2.2.0
    - 3.0.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: v-tooltip
    versions:
    - 2.1.2
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: expect-more-jest
    versions:
    - 5.2.1
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.1
